# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: jamesthespeedy@gmail.com
author_name: James Dietz
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: server
labextension_name: html-toc-export
mimetype: ''
mimetype_name: ''
project_short_description: Export HTML with table of contents
python_name: html_toc_export
repository: https://github.com/mj10021/html-toc-export
test: true
viewer_name: ''

